title: nemo's notebook
description: personal study notes
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
mathjax: true
theme: minima
plugins:
  - jekyll-feed

# Disqus Comments
comments: true
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: strncat.github.io
